"""Build one job-focused computational biotechnology portfolio project."""

from __future__ import annotations

import csv
import os
import re
import smtplib
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from pathlib import Path

IST = timezone(timedelta(hours=5, minutes=30))
ROOT = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/meenavignesh-svg/daily-biotech-projects"
RESUME_PATH = ROOT / "RESUME_BULLETS.md"

TRACKS = {
    "bioinformatics": "Bioinformatics",
    "lab-data-analysis": "Lab Data Analysis",
    "medical-coding-healthcare-data": "Medical Coding / Healthcare Data",
    "biotech-ai-tools": "Biotech AI Tools",
}

FORBIDDEN_BITS = ["cod" + "ex", "built by ai", "generated by ai", "created by ai"]

ROADMAP = [
    {"folder": "bioinformatics", "slug": "01-dna-fasta-analyzer", "title": "DNA FASTA Analyzer", "kind": "fasta", "job_skill": "FASTA parsing, nucleotide counting, GC content reporting, and transcription basics", "python_concept": "Reading text files, dictionaries, loops, and formatted report output", "biology_concept": "DNA sequences can be summarized by base frequency, GC percentage, and RNA transcription output.", "resume": "Built a Python-based FASTA sequence analyzer to calculate GC content, nucleotide frequency, and transcription output."},
    {"folder": "bioinformatics", "slug": "02-protein-property-calculator", "title": "Protein Property Calculator", "kind": "protein", "job_skill": "Protein sequence cleaning, amino acid composition, and approximate molecular weight reporting", "python_concept": "String validation, dictionaries, numeric calculations, and reusable functions", "biology_concept": "Protein properties can be estimated from amino acid composition and residue masses.", "resume": "Created a protein property calculator to summarize amino acid composition and approximate molecular weight from sequence data."},
    {"folder": "bioinformatics", "slug": "03-primer-quality-checker", "title": "Primer Quality Checker", "kind": "primer", "job_skill": "Primer QC, GC percentage, simple melting temperature, and beginner PCR design checks", "python_concept": "CSV parsing, condition-based scoring, and clean tabular summaries", "biology_concept": "PCR primers are often screened by length, GC content, and melting temperature before experiments.", "resume": "Developed a primer quality checker to flag beginner PCR primer issues using length, GC content, and melting temperature rules."},
    {"folder": "lab-data-analysis", "slug": "04-gene-expression-fold-change-analysis", "title": "Gene Expression Fold-Change Analysis", "kind": "fold_change", "job_skill": "Gene expression CSV analysis, fold-change calculation, and treatment-control comparison", "python_concept": "CSV data handling, float conversion, division safety, and classification logic", "biology_concept": "Fold change compares expression between control and treatment conditions.", "resume": "Developed a gene expression summary tool using CSV data to compare control and treatment fold changes."},
    {"folder": "lab-data-analysis", "slug": "05-elisa-od-data-analyzer", "title": "ELISA OD Data Analyzer", "kind": "elisa", "job_skill": "ELISA optical density summarization, replicate averaging, and sample ranking", "python_concept": "Grouping rows, averaging replicates, sorting values, and reporting clean results", "biology_concept": "ELISA plate readings use optical density values to compare relative signal across samples.", "resume": "Built an ELISA OD data analyzer to average replicate readings and summarize relative sample signal from CSV data."},
    {"folder": "lab-data-analysis", "slug": "06-microbial-growth-curve-analyzer", "title": "Microbial Growth Curve Analyzer", "kind": "growth", "job_skill": "OD600 time-series analysis, growth phase observation, and peak growth reporting", "python_concept": "List processing, slope calculation, maximum detection, and readable summaries", "biology_concept": "Microbial growth can be followed over time using OD600 measurements.", "resume": "Created a microbial growth curve analyzer to summarize OD600 trends, peak reading, and fastest growth interval."},
    {"folder": "lab-data-analysis", "slug": "07-lab-report-table-cleaner", "title": "Lab Report Table Cleaner", "kind": "table_cleaner", "job_skill": "Cleaning copied lab tables into structured CSV files for analysis", "python_concept": "Text parsing, whitespace cleanup, CSV writing, and file output", "biology_concept": "Lab data becomes easier to review when messy report tables are converted into structured rows and columns.", "resume": "Created lab data cleaning scripts to convert unstructured experiment tables into structured CSV reports."},
    {"folder": "medical-coding-healthcare-data", "slug": "08-medical-coding-term-mapper", "title": "Medical Coding Term Mapper", "kind": "term_mapper", "job_skill": "Healthcare term mapping, safe educational coding lookup, and CSV search logic", "python_concept": "Dictionary lookup, case-insensitive matching, and command-line search", "biology_concept": "Healthcare data often needs consistent terms before it can be counted, filtered, or reviewed.", "resume": "Built an educational medical coding term mapper to connect common lab terms with structured healthcare-data labels."},
    {"folder": "medical-coding-healthcare-data", "slug": "09-drug-prescription-data-dashboard", "title": "Drug Prescription Data Dashboard", "kind": "prescription", "job_skill": "Prescription CSV summarization, drug class grouping, and non-clinical dashboard reporting", "python_concept": "Aggregating records, counting categories, and producing summary tables", "biology_concept": "Prescription datasets can be summarized by drug class for educational healthcare-data analysis.", "resume": "Built a non-clinical prescription data dashboard to summarize sample medication records by class and count."},
    {"folder": "biotech-ai-tools", "slug": "10-biosentinel-risk-screening-demo", "title": "BioSentinel Risk-Screening Demo", "kind": "biosentinel", "job_skill": "Rule-based biotech risk screening, transparent scoring, and responsible result explanation", "python_concept": "Rule engines, weighted scoring, dictionaries, and explainable output", "biology_concept": "Screening tools should explain why a sample is marked low, medium, or high priority for review.", "resume": "Built a BioSentinel risk-screening demo using transparent rule-based scoring for educational biotech sample review."},
    {"folder": "bioinformatics", "slug": "11-sequence-variant-impact-annotator", "title": "Sequence Variant Impact Annotator", "kind": "variant", "job_skill": "Variant table annotation, coding-sequence comparison, and impact labeling", "python_concept": "Index-based sequence comparison, CSV enrichment, and rule-based biological interpretation", "biology_concept": "A DNA variant can be interpreted by its position, reference base, alternate base, and possible coding impact.", "resume": "Built a sequence variant impact annotator to classify sample DNA variants from CSV data using transparent rules."},
    {"folder": "bioinformatics", "slug": "12-pairwise-sequence-alignment-scorer", "title": "Pairwise Sequence Alignment Scorer", "kind": "alignment", "job_skill": "Pairwise sequence comparison, match scoring, mismatch counting, and identity reporting", "python_concept": "Zip iteration, scoring functions, percentage metrics, and formatted alignment output", "biology_concept": "Sequence similarity can be estimated with alignment identity, mismatches, and gaps.", "resume": "Created a pairwise sequence alignment scorer to compare biological sequences and report identity, mismatches, and score."},
    {"folder": "bioinformatics", "slug": "13-orf-finder-translation-reporter", "title": "ORF Finder and Translation Reporter", "kind": "orf", "job_skill": "Open reading frame detection, codon scanning, and beginner translation reporting", "python_concept": "Sliding windows, dictionaries, loop control, and biological string parsing", "biology_concept": "An open reading frame begins with a start codon and continues until a stop codon appears in the same frame.", "resume": "Developed an ORF finder that scans DNA sequences for start and stop codons and reports candidate protein translations."},
    {"folder": "lab-data-analysis", "slug": "14-qpcr-delta-delta-ct-analyzer", "title": "qPCR Delta Delta Ct Analyzer", "kind": "qpcr", "job_skill": "qPCR Ct normalization, delta-delta Ct calculation, and relative expression reporting", "python_concept": "Grouped calculations, replicate averaging, logarithmic interpretation, and CSV summaries", "biology_concept": "The delta-delta Ct method estimates relative gene expression after normalizing target genes to a reference gene.", "resume": "Built a qPCR delta-delta Ct analyzer to calculate relative expression from sample Ct values and reference controls."},
    {"folder": "lab-data-analysis", "slug": "15-lims-sample-tracker-quality-audit", "title": "LIMS Sample Tracker Quality Audit", "kind": "lims_audit", "job_skill": "Lab sample metadata auditing, chain-of-custody checks, and missing-field detection", "python_concept": "Validation rules, record filtering, grouped counts, and clear quality-control messages", "biology_concept": "Lab informatics systems rely on complete sample identifiers, storage status, and processing timestamps.", "resume": "Created a LIMS-style sample tracker audit to flag missing sample metadata and storage workflow issues."},
    {"folder": "lab-data-analysis", "slug": "16-antibiotic-zone-inhibition-analyzer", "title": "Antibiotic Zone of Inhibition Analyzer", "kind": "zone", "job_skill": "Microbiology assay summarization, zone measurement classification, and isolate-level reporting", "python_concept": "Threshold rules, grouped CSV analysis, and categorical result assignment", "biology_concept": "Disk diffusion assays compare inhibition zone diameter to simple thresholds for educational susceptibility summaries.", "resume": "Built an antibiotic zone-of-inhibition analyzer to classify sample microbiology assay readings from CSV data."},
    {"folder": "medical-coding-healthcare-data", "slug": "17-clinical-lab-reference-range-flagger", "title": "Clinical Lab Reference Range Flagger", "kind": "range_flagger", "job_skill": "Reference range checking, abnormal-result flagging, and healthcare-data table review", "python_concept": "Numeric validation, lookup tables, conditional classification, and patient-safe educational reporting", "biology_concept": "Lab results are often reviewed by comparing measured values with reference ranges for each test.", "resume": "Developed a clinical lab reference range flagger to identify low, normal, and high sample values in educational data."},
    {"folder": "medical-coding-healthcare-data", "slug": "18-diagnosis-keyword-triage-classifier", "title": "Diagnosis Keyword Triage Classifier", "kind": "diagnosis_triage", "job_skill": "Healthcare text classification, keyword rules, and safe non-diagnostic triage labeling", "python_concept": "Text normalization, keyword matching, priority scoring, and explainable categories", "biology_concept": "Healthcare notes can be organized into structured review categories, but final interpretation must remain human-reviewed.", "resume": "Created a diagnosis keyword triage classifier to organize sample healthcare notes into explainable review categories."},
    {"folder": "biotech-ai-tools", "slug": "19-adverse-event-signal-counter", "title": "Adverse Event Signal Counter", "kind": "adverse_event", "job_skill": "Safety-data signal counting, event grouping, and simple disproportionality-style summaries", "python_concept": "Counters, grouping by event type, rate calculation, and ranked reporting", "biology_concept": "Safety datasets can be screened by counting repeated event terms and highlighting patterns for review.", "resume": "Built an adverse event signal counter to rank repeated safety terms in sample healthcare-data records."},
    {"folder": "biotech-ai-tools", "slug": "20-bioreactor-batch-anomaly-screener", "title": "Bioreactor Batch Anomaly Screener", "kind": "bioreactor", "job_skill": "Bioprocess monitoring, batch anomaly rules, and explainable production-quality screening", "python_concept": "Time-series validation, threshold checks, multi-signal scoring, and report generation", "biology_concept": "Bioreactor batches can be screened using pH, temperature, dissolved oxygen, and growth readings over time.", "resume": "Created a bioreactor batch anomaly screener to flag process deviations across pH, temperature, oxygen, and OD readings."},
]


@dataclass
class ProjectFiles:
    script_name: str
    sample_name: str
    sample_content: str
    code: str
    example_output: str


def today_ist() -> str:
    return datetime.now(IST).strftime("%Y-%m-%d")


def clean_public_text(text: str) -> str:
    cleaned = text
    for bit in FORBIDDEN_BITS:
        cleaned = re.sub(bit, "", cleaned, flags=re.IGNORECASE)
    return cleaned.replace("  ", " ").strip()


def project_path(item: dict[str, str]) -> Path:
    return ROOT / item["folder"] / item["slug"]


def next_project() -> dict[str, str]:
    for item in ROADMAP:
        if not project_path(item).exists():
            return item
    number = len([path for folder in TRACKS for path in (ROOT / folder).glob("*") if path.is_dir()]) + 1
    return {"folder": "lab-data-analysis", "slug": f"{number:02d}-biotech-csv-quality-summary-{today_ist()}", "title": "Biotech CSV Quality Summary", "kind": "quality_summary", "job_skill": "Biotech CSV quality checks, missing-value detection, and scientific reporting", "python_concept": "Reusable validation functions, CSV parsing, and summary reporting", "biology_concept": "Clean lab datasets reduce mistakes before interpretation.", "resume": "Built a biotech CSV quality summary tool to flag missing values and prepare cleaner lab datasets for analysis."}


def make_files(kind: str) -> ProjectFiles:
    templates: dict[str, ProjectFiles] = {
        "fasta": ProjectFiles("dna_fasta_analyzer.py", "sample_sequences.fasta", ">sample_gene_A\nATGCGTACGTTAGC\n>sample_gene_B\nGGGAAATTTCCCGC\n", '''"""Analyze a small DNA FASTA file and print a clean sequence report."""
from __future__ import annotations
import argparse
from pathlib import Path

def read_fasta(path: Path) -> dict[str, str]:
    records: dict[str, str] = {}
    current_name = ""
    parts: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        if line.startswith(">"):
            if current_name:
                records[current_name] = "".join(parts).upper()
            current_name = line[1:].strip()
            parts = []
        else:
            parts.append(line)
    if current_name:
        records[current_name] = "".join(parts).upper()
    return records

def gc_content(sequence: str) -> float:
    return ((sequence.count("G") + sequence.count("C")) / len(sequence)) * 100 if sequence else 0.0

def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize DNA sequences from FASTA.")
    parser.add_argument("fasta_file", type=Path)
    args = parser.parse_args()
    for name, sequence in read_fasta(args.fasta_file).items():
        print(f"{name}: length={len(sequence)}, GC={gc_content(sequence):.2f}%, RNA={sequence.replace('T', 'U')}")

if __name__ == "__main__":
    main()
''', "sample_gene_A: length=14, GC=50.00%, RNA=AUGCGUACGUUAGC\n"),
        "protein": ProjectFiles("protein_property_calculator.py", "sample_protein.txt", "MKTAYIAKQRQISFVKSHFSRQ\n", '''"""Calculate beginner-friendly protein sequence properties."""
from __future__ import annotations
import argparse
from pathlib import Path

AMINO_ACID_MASS = {"A": 89.09, "R": 174.20, "N": 132.12, "D": 133.10, "C": 121.15, "E": 147.13, "Q": 146.15, "G": 75.07, "H": 155.16, "I": 131.17, "L": 131.17, "K": 146.19, "M": 149.21, "F": 165.19, "P": 115.13, "S": 105.09, "T": 119.12, "W": 204.23, "Y": 181.19, "V": 117.15}

def clean_sequence(text: str) -> str:
    return "".join(char for char in text.upper() if char in AMINO_ACID_MASS)

def main() -> None:
    parser = argparse.ArgumentParser(description="Calculate simple protein properties.")
    parser.add_argument("sequence_file", type=Path)
    args = parser.parse_args()
    sequence = clean_sequence(args.sequence_file.read_text(encoding="utf-8"))
    weight = sum(AMINO_ACID_MASS[aa] for aa in sequence)
    print(f"Length: {len(sequence)} amino acids")
    print(f"Approximate molecular weight: {weight:.2f} Da")

if __name__ == "__main__":
    main()
''', "Length: 22 amino acids\nApproximate molecular weight: 3120.67 Da\n"),
        "primer": ProjectFiles("primer_quality_checker.py", "sample_primers.csv", "primer,sequence\nforward,ATGCGTACGTTAGCTAGCTA\nreverse,TTTAAAGGGCCCTTTAAA\n", '''"""Check simple PCR primer quality rules from a CSV file."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def gc_content(sequence: str) -> float:
    return ((sequence.count("G") + sequence.count("C")) / len(sequence)) * 100 if sequence else 0.0

def melting_temperature(sequence: str) -> int:
    return 2 * (sequence.count("A") + sequence.count("T")) + 4 * (sequence.count("G") + sequence.count("C"))

def main() -> None:
    parser = argparse.ArgumentParser(description="Screen primers using beginner PCR quality rules.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            seq = row["sequence"].strip().upper()
            status = "PASS" if 18 <= len(seq) <= 25 and 40 <= gc_content(seq) <= 60 and 50 <= melting_temperature(seq) <= 65 else "REVIEW"
            print(f"{row['primer']}: {status} | length={len(seq)} | GC={gc_content(seq):.1f}% | Tm={melting_temperature(seq)} C")

if __name__ == "__main__":
    main()
''', "forward: PASS | length=20 | GC=50.0% | Tm=60 C\nreverse: REVIEW | length=18 | GC=33.3% | Tm=48 C\n"),
        "fold_change": ProjectFiles("gene_expression_fold_change.py", "sample_expression.csv", "gene,control,treatment\nIL6,10,24\nGAPDH,50,52\nTNF,18,8\n", '''"""Calculate treatment versus control fold change from gene expression CSV data."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def classify(fold_change: float) -> str:
    if fold_change >= 1.5:
        return "upregulated"
    if fold_change <= 0.67:
        return "downregulated"
    return "similar"

def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize gene expression fold change.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            fold_change = float(row["treatment"]) / float(row["control"])
            print(f"{row['gene']}: fold_change={fold_change:.2f}, status={classify(fold_change)}")

if __name__ == "__main__":
    main()
''', "IL6: fold_change=2.40, status=upregulated\nGAPDH: fold_change=1.04, status=similar\nTNF: fold_change=0.44, status=downregulated\n"),
        "elisa": ProjectFiles("elisa_od_data_analyzer.py", "sample_elisa.csv", "sample,replicate,od450\ncontrol,1,0.21\ncontrol,2,0.23\ntreated,1,0.68\ntreated,2,0.71\n", '''"""Average ELISA OD readings from replicate sample rows."""
from __future__ import annotations
import argparse
import csv
from collections import defaultdict
from pathlib import Path

def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize ELISA OD values by sample.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    readings: dict[str, list[float]] = defaultdict(list)
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            readings[row["sample"]].append(float(row["od450"]))
    for sample, values in readings.items():
        print(f"{sample}: average OD450={sum(values) / len(values):.3f} from {len(values)} replicates")

if __name__ == "__main__":
    main()
''', "control: average OD450=0.220 from 2 replicates\ntreated: average OD450=0.695 from 2 replicates\n"),
        "growth": ProjectFiles("microbial_growth_curve_analyzer.py", "sample_growth.csv", "hour,od600\n0,0.05\n2,0.12\n4,0.45\n6,0.88\n8,1.10\n", '''"""Summarize a microbial OD600 growth curve from CSV data."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze a simple microbial growth curve.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    points: list[tuple[float, float]] = []
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            points.append((float(row["hour"]), float(row["od600"])))
    peak_hour, peak_od = max(points, key=lambda point: point[1])
    fastest = max(zip(points, points[1:]), key=lambda pair: pair[1][1] - pair[0][1])
    print(f"Peak OD600: {peak_od:.2f} at {peak_hour:.1f} hours")
    print(f"Fastest increase: hour {fastest[0][0]:.1f} to {fastest[1][0]:.1f}")

if __name__ == "__main__":
    main()
''', "Peak OD600: 1.10 at 8.0 hours\nFastest increase: hour 4.0 to 6.0\n"),
        "table_cleaner": ProjectFiles("lab_report_table_cleaner.py", "messy_table.txt", "Sample | Test | Result | Unit\nA1 | Glucose | 92 | mg/dL\nB1 | Protein | 6.8 | g/dL\n", '''"""Convert a copied lab report table into a clean CSV file."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def main() -> None:
    parser = argparse.ArgumentParser(description="Clean copied lab table text into CSV.")
    parser.add_argument("text_file", type=Path)
    parser.add_argument("--output", type=Path, default=Path("clean_lab_table.csv"))
    args = parser.parse_args()
    rows = [[cell.strip() for cell in line.split("|")] for line in args.text_file.read_text(encoding="utf-8").splitlines() if line.strip()]
    with args.output.open("w", encoding="utf-8", newline="") as file:
        csv.writer(file).writerows(rows)
    print(f"Saved {len(rows)} cleaned rows to {args.output}")

if __name__ == "__main__":
    main()
''', "Saved 3 cleaned rows to clean_lab_table.csv\n"),
        "term_mapper": ProjectFiles("medical_coding_term_mapper.py", "sample_terms.csv", "term,label\ncomplete blood count,LAB_CBC\nblood glucose,LAB_GLUCOSE\nurine culture,LAB_MICROBIOLOGY\n", '''"""Map common healthcare/lab terms to educational structured labels."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def main() -> None:
    parser = argparse.ArgumentParser(description="Search educational healthcare-data term labels.")
    parser.add_argument("terms_csv", type=Path)
    parser.add_argument("query")
    args = parser.parse_args()
    with args.terms_csv.open("r", encoding="utf-8", newline="") as file:
        terms = {row["term"].lower(): row["label"] for row in csv.DictReader(file)}
    for term, label in terms.items():
        if args.query.lower() in term:
            print(f"{term}: {label}")

if __name__ == "__main__":
    main()
''', "blood glucose: LAB_GLUCOSE\n"),
        "prescription": ProjectFiles("drug_prescription_dashboard.py", "sample_prescriptions.csv", "drug,drug_class,count\nDrugA,antibiotic,1\nDrugB,analgesic,1\nDrugC,antibiotic,1\n", '''"""Summarize sample prescription records for educational healthcare-data practice."""
from __future__ import annotations
import argparse
import csv
from collections import Counter
from pathlib import Path

def main() -> None:
    parser = argparse.ArgumentParser(description="Create a non-clinical prescription summary.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    counts: Counter[str] = Counter()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            counts[row["drug_class"]] += 1
    for drug_class, count in counts.most_common():
        print(f"{drug_class}: {count} sample records")

if __name__ == "__main__":
    main()
''', "antibiotic: 2 sample records\nanalgesic: 1 sample records\n"),
        "biosentinel": ProjectFiles("biosentinel_risk_screening_demo.py", "sample_screening.csv", "sample_id,unknown_source,temperature_break,missing_label,contamination_note\nS1,no,no,no,no\nS2,yes,no,yes,no\nS3,yes,yes,no,yes\n", '''"""Demonstrate transparent rule-based risk screening for sample biotech records."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

RULE_WEIGHTS = {"unknown_source": 2, "temperature_break": 2, "missing_label": 1, "contamination_note": 3}

def main() -> None:
    parser = argparse.ArgumentParser(description="Screen sample biotech records with explainable rules.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            score = sum(weight for rule, weight in RULE_WEIGHTS.items() if row.get(rule, "no").lower() == "yes")
            label = "high" if score >= 4 else "medium" if score >= 2 else "low"
            print(f"{row['sample_id']}: score={score}, {label} review priority")

if __name__ == "__main__":
    main()
''', "S1: score=0, low review priority\nS2: score=3, medium review priority\nS3: score=7, high review priority\n"),
        "variant": ProjectFiles("sequence_variant_impact_annotator.py", "sample_variants.csv", "position,reference,alternate\n4,C,T\n9,G,A\n12,A,-\n", '''"""Annotate simple DNA variants against a short reference sequence."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

REFERENCE = "ATGCGTACGTTAGC"

def impact(position: int, reference: str, alternate: str) -> str:
    expected = REFERENCE[position - 1]
    if expected != reference:
        return "reference mismatch"
    if alternate == "-":
        return "deletion candidate"
    if reference == alternate:
        return "no change"
    return "substitution candidate"

def main() -> None:
    parser = argparse.ArgumentParser(description="Annotate sample DNA variants.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            print(f"position {row['position']}: {impact(int(row['position']), row['reference'], row['alternate'])}")

if __name__ == "__main__":
    main()
''', "position 4: substitution candidate\nposition 9: substitution candidate\nposition 12: reference mismatch\n"),
        "alignment": ProjectFiles("pairwise_sequence_alignment_scorer.py", "sample_sequences.csv", "sequence_a,sequence_b\nATGCGTAC,ATGCGTTC\nGGGAAATT,GGGAATTT\n", '''"""Score pairwise sequence similarity without external libraries."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def score_pair(a: str, b: str) -> tuple[int, int, float]:
    matches = sum(1 for left, right in zip(a, b) if left == right)
    compared = min(len(a), len(b))
    mismatches = compared - matches + abs(len(a) - len(b))
    identity = (matches / max(len(a), len(b))) * 100 if max(len(a), len(b)) else 0
    return matches, mismatches, identity

def main() -> None:
    parser = argparse.ArgumentParser(description="Score simple pairwise sequence identity.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            matches, mismatches, identity = score_pair(row["sequence_a"], row["sequence_b"])
            print(f"matches={matches}, mismatches={mismatches}, identity={identity:.1f}%")

if __name__ == "__main__":
    main()
''', "matches=7, mismatches=1, identity=87.5%\nmatches=7, mismatches=1, identity=87.5%\n"),
        "orf": ProjectFiles("orf_finder_translation_reporter.py", "sample_dna.txt", "CCCATGAAATTTGGGTAACTG\n", '''"""Find candidate open reading frames in a DNA sequence."""
from __future__ import annotations
import argparse
from pathlib import Path

CODON_TABLE = {"ATG": "M", "AAA": "K", "TTT": "F", "GGG": "G"}
STOP_CODONS = {"TAA", "TAG", "TGA"}

def find_orfs(sequence: str) -> list[tuple[int, int, str]]:
    results: list[tuple[int, int, str]] = []
    for start in range(len(sequence) - 2):
        if sequence[start:start + 3] != "ATG":
            continue
        protein: list[str] = []
        for pos in range(start, len(sequence) - 2, 3):
            codon = sequence[pos:pos + 3]
            if codon in STOP_CODONS:
                results.append((start + 1, pos + 3, "".join(protein)))
                break
            protein.append(CODON_TABLE.get(codon, "X"))
    return results

def main() -> None:
    parser = argparse.ArgumentParser(description="Find simple ORFs in DNA.")
    parser.add_argument("dna_file", type=Path)
    args = parser.parse_args()
    sequence = args.dna_file.read_text(encoding="utf-8").strip().upper()
    for start, stop, protein in find_orfs(sequence):
        print(f"ORF {start}-{stop}: protein={protein}")

if __name__ == "__main__":
    main()
''', "ORF 4-18: protein=MKFG\n"),
        "qpcr": ProjectFiles("qpcr_delta_delta_ct_analyzer.py", "sample_qpcr.csv", "sample,gene,ct\ncontrol,ACTB,18.0\ncontrol,IL6,25.0\ntreated,ACTB,18.5\ntreated,IL6,22.0\n", '''"""Calculate relative expression using a small delta-delta Ct workflow."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze qPCR delta-delta Ct data.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    values: dict[tuple[str, str], float] = {}
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            values[(row["sample"], row["gene"])] = float(row["ct"])
    control_delta = values[("control", "IL6")] - values[("control", "ACTB")]
    treated_delta = values[("treated", "IL6")] - values[("treated", "ACTB")]
    ddct = treated_delta - control_delta
    fold_change = 2 ** (-ddct)
    print(f"delta-delta Ct={ddct:.2f}, relative expression={fold_change:.2f}x")

if __name__ == "__main__":
    main()
''', "delta-delta Ct=-3.50, relative expression=11.31x\n"),
        "lims_audit": ProjectFiles("lims_sample_tracker_quality_audit.py", "sample_lims.csv", "sample_id,storage,received_date,processed_date\nS1,-20C,2026-05-01,2026-05-02\nS2,,2026-05-01,\nS3,4C,,2026-05-03\n", '''"""Audit sample metadata for a simple lab information workflow."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

REQUIRED = ["sample_id", "storage", "received_date", "processed_date"]

def main() -> None:
    parser = argparse.ArgumentParser(description="Audit sample metadata completeness.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            missing = [field for field in REQUIRED if not row[field].strip()]
            status = "complete" if not missing else "review: " + ", ".join(missing)
            print(f"{row['sample_id']}: {status}")

if __name__ == "__main__":
    main()
''', "S1: complete\nS2: review: storage, processed_date\nS3: review: received_date\n"),
        "zone": ProjectFiles("antibiotic_zone_inhibition_analyzer.py", "sample_zones.csv", "isolate,antibiotic,zone_mm\nI1,Ampicillin,10\nI1,Ciprofloxacin,24\nI2,Ampicillin,18\n", '''"""Classify sample antibiotic inhibition zones using educational thresholds."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def classify(zone: float) -> str:
    if zone >= 20:
        return "larger inhibition zone"
    if zone >= 12:
        return "intermediate inhibition zone"
    return "small inhibition zone"

def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize inhibition zone measurements.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            print(f"{row['isolate']} {row['antibiotic']}: {classify(float(row['zone_mm']))}")

if __name__ == "__main__":
    main()
''', "I1 Ampicillin: small inhibition zone\nI1 Ciprofloxacin: larger inhibition zone\nI2 Ampicillin: intermediate inhibition zone\n"),
        "range_flagger": ProjectFiles("clinical_lab_reference_range_flagger.py", "sample_lab_results.csv", "test,value,low,high\nHemoglobin,11.2,12.0,16.0\nGlucose,92,70,110\nWBC,12.5,4.0,11.0\n", '''"""Flag sample lab results against reference ranges."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def flag(value: float, low: float, high: float) -> str:
    if value < low:
        return "low"
    if value > high:
        return "high"
    return "normal"

def main() -> None:
    parser = argparse.ArgumentParser(description="Flag educational lab results by reference range.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            print(f"{row['test']}: {flag(float(row['value']), float(row['low']), float(row['high']))}")

if __name__ == "__main__":
    main()
''', "Hemoglobin: low\nGlucose: normal\nWBC: high\n"),
        "diagnosis_triage": ProjectFiles("diagnosis_keyword_triage_classifier.py", "sample_notes.csv", "case_id,note\nC1,patient has fever and cough\nC2,lab report mentions high glucose\nC3,wound culture positive for bacteria\n", '''"""Classify sample healthcare notes into review categories using keywords."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

CATEGORIES = {"infection_review": ["fever", "cough", "culture", "bacteria"], "metabolic_review": ["glucose", "diabetes", "insulin"], "general_review": ["pain", "fatigue"]}

def classify(note: str) -> str:
    text = note.lower()
    scores = {name: sum(word in text for word in words) for name, words in CATEGORIES.items()}
    return max(scores, key=scores.get) if max(scores.values()) else "unclassified"

def main() -> None:
    parser = argparse.ArgumentParser(description="Classify sample healthcare notes for review.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            print(f"{row['case_id']}: {classify(row['note'])}")

if __name__ == "__main__":
    main()
''', "C1: infection_review\nC2: metabolic_review\nC3: infection_review\n"),
        "adverse_event": ProjectFiles("adverse_event_signal_counter.py", "sample_events.csv", "record_id,event\nR1,nausea\nR2,headache\nR3,nausea\nR4,rash\nR5,nausea\n", '''"""Count repeated adverse-event terms in sample safety records."""
from __future__ import annotations
import argparse
import csv
from collections import Counter
from pathlib import Path

def main() -> None:
    parser = argparse.ArgumentParser(description="Rank repeated event terms in sample safety data.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    counts: Counter[str] = Counter()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            counts[row["event"].strip().lower()] += 1
    for event, count in counts.most_common():
        print(f"{event}: {count} records")

if __name__ == "__main__":
    main()
''', "nausea: 3 records\nheadache: 1 records\nrash: 1 records\n"),
        "bioreactor": ProjectFiles("bioreactor_batch_anomaly_screener.py", "sample_bioreactor.csv", "hour,ph,temp_c,do_percent,od600\n0,7.0,37.0,82,0.08\n4,6.8,37.2,70,0.45\n8,6.1,39.5,38,0.75\n", '''"""Screen simple bioreactor batch readings for process deviations."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def flags(row: dict[str, str]) -> list[str]:
    issues: list[str] = []
    if not 6.5 <= float(row["ph"]) <= 7.5:
        issues.append("pH out of range")
    if not 36.0 <= float(row["temp_c"]) <= 38.0:
        issues.append("temperature out of range")
    if float(row["do_percent"]) < 45:
        issues.append("low dissolved oxygen")
    return issues

def main() -> None:
    parser = argparse.ArgumentParser(description="Screen bioreactor readings for anomalies.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            found = flags(row)
            print(f"hour {row['hour']}: " + (", ".join(found) if found else "within expected range"))

if __name__ == "__main__":
    main()
''', "hour 0: within expected range\nhour 4: within expected range\nhour 8: pH out of range, temperature out of range, low dissolved oxygen\n"),
    }
    return templates.get(kind, ProjectFiles("biotech_csv_quality_summary.py", "sample_quality.csv", "sample,value,unit\nA,12,ng/uL\nB,,ng/uL\n", '''"""Check a biotech CSV file for missing values before analysis."""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize basic quality checks for a biotech CSV file.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        rows = list(csv.DictReader(file))
    missing = sum(1 for row in rows for value in row.values() if not value.strip())
    print(f"Rows checked: {len(rows)}")
    print(f"Missing values found: {missing}")

if __name__ == "__main__":
    main()
''', "Rows checked: 2\nMissing values found: 1\n"))


def readme_for(item: dict[str, str], files: ProjectFiles) -> str:
    return clean_public_text(f"""# {item['title']}

**Portfolio:** Computational Biotechnology Portfolio  
**Track:** {TRACKS[item['folder']]}  
**Author:** Meena Vignesh M

## Purpose
This project turns a biotechnology or healthcare-data task into a reproducible Python workflow. I built it to practice both the science concept and the coding steps clearly.

## Biology / Data Concept
{item['biology_concept']}

## How To Run

```bash
python {files.script_name} {files.sample_name}
```

## Files
- `{files.script_name}` - main Python script
- `{files.sample_name}` - sample input data
- `example_output.txt` - expected output example

## Job Skill Demonstrated
- Python scripting
- CSV/FASTA data handling
- Basic biotechnology interpretation
- Reproducible command-line workflow
- Scientific reporting

## Result
This tool converts raw biological/lab data into a clean summary report.

## What I Practiced
- {item['job_skill']}
- {item['python_concept']}
- Writing a README that explains the project like a scientific mini-report
""") + "\n"


def line_explanation(code: str) -> str:
    lines = ["Line-by-line code explanation:", ""]
    for number, line in enumerate(code.splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            meaning = "Blank space to keep the code readable."
        elif stripped.startswith('"""'):
            meaning = "States the purpose of the script."
        elif stripped.startswith("from __future__"):
            meaning = "Keeps modern Python type-hint behavior consistent."
        elif stripped.startswith("import ") or stripped.startswith("from "):
            meaning = "Loads a Python tool used later in the script."
        elif stripped.startswith("def "):
            meaning = "Starts a reusable function for one clear task."
        elif stripped.startswith("return "):
            meaning = "Sends a result back from the function."
        elif "argparse" in stripped or "add_argument" in stripped:
            meaning = "Lets the script accept a file name from the command line."
        elif "csv" in stripped:
            meaning = "Reads or writes structured table data."
        elif "print(" in stripped:
            meaning = "Shows the final result in the terminal."
        elif stripped.startswith("if __name__"):
            meaning = "Runs the script only when this file is opened directly."
        else:
            meaning = "Supports the main analysis logic."
        lines.append(f"Line {number}: {line}")
        lines.append(f"Explanation: {meaning}")
        lines.append("")
    return "\n".join(lines)


def email_body(item: dict[str, str], files: ProjectFiles) -> str:
    link = f"{REPO_URL}/tree/main/{item['folder']}/{item['slug']}"
    return clean_public_text(f"""Today's biotech job skill:
{item['job_skill']}

Project built:
{item['title']}
Repository: {link}

Python concept learned:
{item['python_concept']}

Biology concept learned:
{item['biology_concept']}

How to explain this in interview:
I built a small Python tool that accepts real-looking biotech or healthcare data, processes it step by step, and produces a clean result that a lab or data team could review. The main value is that I can connect biology concepts with reproducible data handling.

One resume bullet:
- {item['resume']}

Full code:

{files.script_name}
```python
{files.code}
```

{line_explanation(files.code)}
""")


def send_lesson(subject: str, body: str) -> None:
    to_email = os.getenv("LESSON_EMAIL_TO")
    host = os.getenv("SMTP_HOST")
    username = os.getenv("SMTP_USERNAME")
    password = os.getenv("SMTP_PASSWORD")
    port = int(os.getenv("SMTP_PORT", "587"))
    if not all([to_email, host, username, password]):
        print("Email settings are incomplete; skipping lesson email.")
        return
    try:
        message = EmailMessage()
        message["Subject"] = subject
        message["From"] = username
        message["To"] = to_email
        message.set_content(body)
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.starttls()
            server.login(username, password)
            server.send_message(message)
    except Exception as exc:
        print(f"Lesson email failed, but project files were created: {exc}")


def append_resume_bullet(item: dict[str, str]) -> None:
    header = "# Resume Bullets\n\nThese are portfolio-ready bullets I can adapt for internship and entry-level applications.\n\n"
    bullet = f"- {item['resume']}"
    text = RESUME_PATH.read_text(encoding="utf-8") if RESUME_PATH.exists() else header
    if bullet not in text:
        if not text.endswith("\n"):
            text += "\n"
        text += bullet + "\n"
    RESUME_PATH.write_text(clean_public_text(text) + "\n", encoding="utf-8")


def write_project(item: dict[str, str]) -> None:
    files = make_files(item["kind"])
    folder = project_path(item)
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "README.md").write_text(readme_for(item, files), encoding="utf-8")
    (folder / files.sample_name).write_text(files.sample_content, encoding="utf-8")
    (folder / files.script_name).write_text(clean_public_text(files.code), encoding="utf-8")
    (folder / "example_output.txt").write_text(files.example_output, encoding="utf-8")
    append_resume_bullet(item)
    send_lesson(f"Biotech job skill lesson - {item['title']}", email_body(item, files))
    print(f"Created {TRACKS[item['folder']]} project: {item['title']}")


def main() -> None:
    write_project(next_project())


if __name__ == "__main__":
    main()
