"""Build one job-focused computational biotechnology portfolio project."""

from __future__ import annotations

import csv
import os
import re
import smtplib
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from pathlib import Path

IST = timezone(timedelta(hours=5, minutes=30))
ROOT = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/meenavignesh-svg/daily-biotech-projects"
RESUME_PATH = ROOT / "RESUME_BULLETS.md"

TRACKS = {
    "bioinformatics": "Bioinformatics",
    "lab-data-analysis": "Lab Data Analysis",
    "medical-coding-healthcare-data": "Medical Coding / Healthcare Data",
    "biotech-ai-tools": "Biotech AI Tools",
}

FORBIDDEN_BITS = ["cod" + "ex", "built by ai", "generated by ai", "created by ai"]

ROADMAP = [
    {
        "folder": "bioinformatics",
        "slug": "01-dna-fasta-analyzer",
        "title": "DNA FASTA Analyzer",
        "kind": "fasta",
        "job_skill": "FASTA parsing, nucleotide counting, GC content reporting, and transcription basics",
        "python_concept": "Reading text files, dictionaries, loops, and formatted report output",
        "biology_concept": "DNA sequences can be summarized by base frequency, GC percentage, and RNA transcription output.",
        "resume": "Built a Python-based FASTA sequence analyzer to calculate GC content, nucleotide frequency, and transcription output.",
    },
    {
        "folder": "bioinformatics",
        "slug": "02-protein-property-calculator",
        "title": "Protein Property Calculator",
        "kind": "protein",
        "job_skill": "Protein sequence cleaning, amino acid composition, and approximate molecular weight reporting",
        "python_concept": "String validation, dictionaries, numeric calculations, and reusable functions",
        "biology_concept": "Protein properties can be estimated from amino acid composition and residue masses.",
        "resume": "Created a protein property calculator to summarize amino acid composition and approximate molecular weight from sequence data.",
    },
    {
        "folder": "bioinformatics",
        "slug": "03-primer-quality-checker",
        "title": "Primer Quality Checker",
        "kind": "primer",
        "job_skill": "Primer QC, GC percentage, simple melting temperature, and beginner PCR design checks",
        "python_concept": "CSV parsing, condition-based scoring, and clean tabular summaries",
        "biology_concept": "PCR primers are often screened by length, GC content, and melting temperature before experiments.",
        "resume": "Developed a primer quality checker to flag beginner PCR primer issues using length, GC content, and melting temperature rules.",
    },
    {
        "folder": "lab-data-analysis",
        "slug": "04-gene-expression-fold-change-analysis",
        "title": "Gene Expression Fold-Change Analysis",
        "kind": "fold_change",
        "job_skill": "Gene expression CSV analysis, fold-change calculation, and treatment-control comparison",
        "python_concept": "CSV data handling, float conversion, division safety, and classification logic",
        "biology_concept": "Fold change compares expression between control and treatment conditions.",
        "resume": "Developed a gene expression summary tool using CSV data to compare control and treatment fold changes.",
    },
    {
        "folder": "lab-data-analysis",
        "slug": "05-elisa-od-data-analyzer",
        "title": "ELISA OD Data Analyzer",
        "kind": "elisa",
        "job_skill": "ELISA optical density summarization, replicate averaging, and sample ranking",
        "python_concept": "Grouping rows, averaging replicates, sorting values, and reporting clean results",
        "biology_concept": "ELISA plate readings use optical density values to compare relative signal across samples.",
        "resume": "Built an ELISA OD data analyzer to average replicate readings and summarize relative sample signal from CSV data.",
    },
    {
        "folder": "lab-data-analysis",
        "slug": "06-microbial-growth-curve-analyzer",
        "title": "Microbial Growth Curve Analyzer",
        "kind": "growth",
        "job_skill": "OD600 time-series analysis, growth phase observation, and peak growth reporting",
        "python_concept": "List processing, slope calculation, maximum detection, and readable summaries",
        "biology_concept": "Microbial growth can be followed over time using OD600 measurements.",
        "resume": "Created a microbial growth curve analyzer to summarize OD600 trends, peak reading, and fastest growth interval.",
    },
    {
        "folder": "lab-data-analysis",
        "slug": "07-lab-report-table-cleaner",
        "title": "Lab Report Table Cleaner",
        "kind": "table_cleaner",
        "job_skill": "Cleaning copied lab tables into structured CSV files for analysis",
        "python_concept": "Text parsing, whitespace cleanup, CSV writing, and file output",
        "biology_concept": "Lab data becomes easier to review when messy report tables are converted into structured rows and columns.",
        "resume": "Created lab data cleaning scripts to convert unstructured experiment tables into structured CSV reports.",
    },
    {
        "folder": "medical-coding-healthcare-data",
        "slug": "08-medical-coding-term-mapper",
        "title": "Medical Coding Term Mapper",
        "kind": "term_mapper",
        "job_skill": "Healthcare term mapping, safe educational coding lookup, and CSV search logic",
        "python_concept": "Dictionary lookup, case-insensitive matching, and command-line search",
        "biology_concept": "Healthcare data often needs consistent terms before it can be counted, filtered, or reviewed.",
        "resume": "Built an educational medical coding term mapper to connect common lab terms with structured healthcare-data labels.",
    },
    {
        "folder": "medical-coding-healthcare-data",
        "slug": "09-drug-prescription-data-dashboard",
        "title": "Drug Prescription Data Dashboard",
        "kind": "prescription",
        "job_skill": "Prescription CSV summarization, drug class grouping, and non-clinical dashboard reporting",
        "python_concept": "Aggregating records, counting categories, and producing summary tables",
        "biology_concept": "Prescription datasets can be summarized by drug class for educational healthcare-data analysis.",
        "resume": "Built a non-clinical prescription data dashboard to summarize sample medication records by class and count.",
    },
    {
        "folder": "biotech-ai-tools",
        "slug": "10-biosentinel-risk-screening-demo",
        "title": "BioSentinel Risk-Screening Demo",
        "kind": "biosentinel",
        "job_skill": "Rule-based biotech risk screening, transparent scoring, and responsible result explanation",
        "python_concept": "Rule engines, weighted scoring, dictionaries, and explainable output",
        "biology_concept": "Screening tools should explain why a sample is marked low, medium, or high priority for review.",
        "resume": "Built a BioSentinel risk-screening demo using transparent rule-based scoring for educational biotech sample review.",
    },
]


@dataclass
class ProjectFiles:
    script_name: str
    sample_name: str
    sample_content: str
    code: str
    example_output: str


def today_ist() -> str:
    return datetime.now(IST).strftime("%Y-%m-%d")


def clean_public_text(text: str) -> str:
    cleaned = text
    for bit in FORBIDDEN_BITS:
        cleaned = re.sub(bit, "", cleaned, flags=re.IGNORECASE)
    return cleaned.replace("  ", " ").strip()


def project_path(item: dict[str, str]) -> Path:
    return ROOT / item["folder"] / item["slug"]


def next_project() -> dict[str, str]:
    for item in ROADMAP:
        if not project_path(item).exists():
            return item
    date_slug = today_ist()
    number = len([path for folder in TRACKS for path in (ROOT / folder).glob("*") if path.is_dir()]) + 1
    return {
        "folder": "lab-data-analysis",
        "slug": f"{number:02d}-biotech-csv-quality-summary-{date_slug}",
        "title": "Biotech CSV Quality Summary",
        "kind": "quality_summary",
        "job_skill": "Biotech CSV quality checks, missing-value detection, and scientific reporting",
        "python_concept": "Reusable validation functions, CSV parsing, and summary reporting",
        "biology_concept": "Clean lab datasets reduce mistakes before interpretation.",
        "resume": "Built a biotech CSV quality summary tool to flag missing values and prepare cleaner lab datasets for analysis.",
    }


def make_files(kind: str) -> ProjectFiles:
    if kind == "fasta":
        code = '''"""Analyze a small DNA FASTA file and print a clean sequence report."""

from __future__ import annotations

import argparse
from pathlib import Path


def read_fasta(path: Path) -> dict[str, str]:
    records: dict[str, str] = {}
    current_name = ""
    parts: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        if line.startswith(">"):
            if current_name:
                records[current_name] = "".join(parts).upper()
            current_name = line[1:].strip()
            parts = []
        else:
            parts.append(line)
    if current_name:
        records[current_name] = "".join(parts).upper()
    return records


def gc_content(sequence: str) -> float:
    if not sequence:
        return 0.0
    gc_count = sequence.count("G") + sequence.count("C")
    return (gc_count / len(sequence)) * 100


def transcribe(sequence: str) -> str:
    return sequence.replace("T", "U")


def summarize(records: dict[str, str]) -> str:
    lines = ["DNA FASTA Analyzer", ""]
    for name, sequence in records.items():
        counts = {base: sequence.count(base) for base in "ATGC"}
        lines.append(f"Sequence: {name}")
        lines.append(f"Length: {len(sequence)} bases")
        lines.append(f"A={counts['A']} T={counts['T']} G={counts['G']} C={counts['C']}")
        lines.append(f"GC content: {gc_content(sequence):.2f}%")
        lines.append(f"RNA transcript: {transcribe(sequence)}")
        lines.append("")
    return "\n".join(lines).rstrip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize DNA sequences from a FASTA file.")
    parser.add_argument("fasta_file", type=Path)
    args = parser.parse_args()
    print(summarize(read_fasta(args.fasta_file)))


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("dna_fasta_analyzer.py", "sample_sequences.fasta", ">sample_gene_A\nATGCGTACGTTAGC\n>sample_gene_B\nGGGAAATTTCCCGC\n", code, "DNA FASTA Analyzer\n\nSequence: sample_gene_A\nLength: 14 bases\nA=3 T=4 G=4 C=3\nGC content: 50.00%\nRNA transcript: AUGCGUACGUUAGC\n")
    if kind == "protein":
        code = '''"""Calculate beginner-friendly protein sequence properties."""

from __future__ import annotations

import argparse
from pathlib import Path

AMINO_ACID_MASS = {
    "A": 89.09, "R": 174.20, "N": 132.12, "D": 133.10, "C": 121.15,
    "E": 147.13, "Q": 146.15, "G": 75.07, "H": 155.16, "I": 131.17,
    "L": 131.17, "K": 146.19, "M": 149.21, "F": 165.19, "P": 115.13,
    "S": 105.09, "T": 119.12, "W": 204.23, "Y": 181.19, "V": 117.15,
}


def clean_sequence(text: str) -> str:
    return "".join(char for char in text.upper() if char in AMINO_ACID_MASS)


def molecular_weight(sequence: str) -> float:
    return sum(AMINO_ACID_MASS[aa] for aa in sequence)


def composition(sequence: str) -> dict[str, int]:
    return {aa: sequence.count(aa) for aa in sorted(set(sequence))}


def main() -> None:
    parser = argparse.ArgumentParser(description="Calculate simple protein properties.")
    parser.add_argument("sequence_file", type=Path)
    args = parser.parse_args()
    sequence = clean_sequence(args.sequence_file.read_text(encoding="utf-8"))
    print("Protein Property Calculator")
    print(f"Length: {len(sequence)} amino acids")
    print(f"Approximate molecular weight: {molecular_weight(sequence):.2f} Da")
    print("Composition:")
    for amino_acid, count in composition(sequence).items():
        print(f"  {amino_acid}: {count}")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("protein_property_calculator.py", "sample_protein.txt", "MKTAYIAKQRQISFVKSHFSRQ\n", code, "Protein Property Calculator\nLength: 22 amino acids\nApproximate molecular weight: 3120.67 Da\n")
    if kind == "primer":
        code = '''"""Check simple PCR primer quality rules from a CSV file."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def gc_content(sequence: str) -> float:
    return ((sequence.count("G") + sequence.count("C")) / len(sequence)) * 100 if sequence else 0.0


def melting_temperature(sequence: str) -> int:
    return 2 * (sequence.count("A") + sequence.count("T")) + 4 * (sequence.count("G") + sequence.count("C"))


def primer_status(sequence: str) -> str:
    length_ok = 18 <= len(sequence) <= 25
    gc_ok = 40 <= gc_content(sequence) <= 60
    tm_ok = 50 <= melting_temperature(sequence) <= 65
    return "PASS" if length_ok and gc_ok and tm_ok else "REVIEW"


def main() -> None:
    parser = argparse.ArgumentParser(description="Screen primers using beginner PCR quality rules.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            sequence = row["sequence"].strip().upper()
            print(f"{row['primer']}: {primer_status(sequence)} | length={len(sequence)} | GC={gc_content(sequence):.1f}% | Tm={melting_temperature(sequence)} C")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("primer_quality_checker.py", "sample_primers.csv", "primer,sequence\nforward,ATGCGTACGTTAGCTAGCTA\nreverse,TTTAAAGGGCCCTTTAAA\n", code, "forward: PASS | length=20 | GC=50.0% | Tm=60 C\nreverse: REVIEW | length=18 | GC=33.3% | Tm=48 C\n")
    if kind == "fold_change":
        code = '''"""Calculate treatment versus control fold change from gene expression CSV data."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def classify(fold_change: float) -> str:
    if fold_change >= 1.5:
        return "upregulated"
    if fold_change <= 0.67:
        return "downregulated"
    return "similar"


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize gene expression fold change.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    print("Gene Expression Fold-Change Analysis")
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            control = float(row["control"])
            treatment = float(row["treatment"])
            fold_change = treatment / control if control else 0.0
            print(f"{row['gene']}: fold_change={fold_change:.2f}, status={classify(fold_change)}")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("gene_expression_fold_change.py", "sample_expression.csv", "gene,control,treatment\nIL6,10,24\nGAPDH,50,52\nTNF,18,8\n", code, "IL6: fold_change=2.40, status=upregulated\nGAPDH: fold_change=1.04, status=similar\nTNF: fold_change=0.44, status=downregulated\n")
    if kind == "elisa":
        code = '''"""Average ELISA OD readings from replicate sample rows."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize ELISA OD values by sample.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    readings: dict[str, list[float]] = defaultdict(list)
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            readings[row["sample"]].append(float(row["od450"]))
    print("ELISA OD Data Analyzer")
    for sample, values in sorted(readings.items(), key=lambda item: sum(item[1]) / len(item[1]), reverse=True):
        average = sum(values) / len(values)
        print(f"{sample}: average OD450={average:.3f} from {len(values)} replicates")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("elisa_od_data_analyzer.py", "sample_elisa.csv", "sample,replicate,od450\ncontrol,1,0.21\ncontrol,2,0.23\ntreated,1,0.68\ntreated,2,0.71\n", code, "treated: average OD450=0.695 from 2 replicates\ncontrol: average OD450=0.220 from 2 replicates\n")
    if kind == "growth":
        code = '''"""Summarize a microbial OD600 growth curve from CSV data."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze a simple microbial growth curve.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    points: list[tuple[float, float]] = []
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            points.append((float(row["hour"]), float(row["od600"])))
    peak_hour, peak_od = max(points, key=lambda point: point[1])
    fastest = max(zip(points, points[1:]), key=lambda pair: pair[1][1] - pair[0][1])
    print("Microbial Growth Curve Analyzer")
    print(f"Peak OD600: {peak_od:.2f} at {peak_hour:.1f} hours")
    print(f"Fastest increase: hour {fastest[0][0]:.1f} to {fastest[1][0]:.1f}")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("microbial_growth_curve_analyzer.py", "sample_growth.csv", "hour,od600\n0,0.05\n2,0.12\n4,0.45\n6,0.88\n8,1.10\n", code, "Peak OD600: 1.10 at 8.0 hours\nFastest increase: hour 4.0 to 6.0\n")
    if kind == "table_cleaner":
        code = '''"""Convert a copied lab report table into a clean CSV file."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def parse_table(text: str) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in text.splitlines():
        if line.strip():
            rows.append([cell.strip() for cell in line.split("|")])
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean copied lab table text into CSV.")
    parser.add_argument("text_file", type=Path)
    parser.add_argument("--output", type=Path, default=Path("clean_lab_table.csv"))
    args = parser.parse_args()
    rows = parse_table(args.text_file.read_text(encoding="utf-8"))
    with args.output.open("w", encoding="utf-8", newline="") as file:
        csv.writer(file).writerows(rows)
    print(f"Saved {len(rows)} cleaned rows to {args.output}")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("lab_report_table_cleaner.py", "messy_table.txt", "Sample | Test | Result | Unit\nA1 | Glucose | 92 | mg/dL\nB1 | Protein | 6.8 | g/dL\n", code, "Saved 3 cleaned rows to clean_lab_table.csv\n")
    if kind == "term_mapper":
        code = '''"""Map common healthcare/lab terms to educational structured labels."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def load_terms(path: Path) -> dict[str, str]:
    with path.open("r", encoding="utf-8", newline="") as file:
        return {row["term"].lower(): row["label"] for row in csv.DictReader(file)}


def main() -> None:
    parser = argparse.ArgumentParser(description="Search educational healthcare-data term labels.")
    parser.add_argument("terms_csv", type=Path)
    parser.add_argument("query")
    args = parser.parse_args()
    terms = load_terms(args.terms_csv)
    query = args.query.lower()
    matches = [(term, label) for term, label in terms.items() if query in term]
    for term, label in matches:
        print(f"{term}: {label}")
    if not matches:
        print("No matching educational label found.")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("medical_coding_term_mapper.py", "sample_terms.csv", "term,label\ncomplete blood count,LAB_CBC\nblood glucose,LAB_GLUCOSE\nurine culture,LAB_MICROBIOLOGY\n", code, "blood glucose: LAB_GLUCOSE\n")
    if kind == "prescription":
        code = '''"""Summarize sample prescription records for educational healthcare-data practice."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a non-clinical prescription summary.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    class_counts: Counter[str] = Counter()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            class_counts[row["drug_class"]] += 1
    print("Drug Prescription Data Dashboard")
    for drug_class, count in class_counts.most_common():
        print(f"{drug_class}: {count} sample records")
    print("Note: This is for data practice only, not medical advice.")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("drug_prescription_dashboard.py", "sample_prescriptions.csv", "drug,drug_class,count\nDrugA,antibiotic,1\nDrugB,analgesic,1\nDrugC,antibiotic,1\n", code, "antibiotic: 2 sample records\nanalgesic: 1 sample records\nNote: This is for data practice only, not medical advice.\n")
    if kind == "biosentinel":
        code = '''"""Demonstrate transparent rule-based risk screening for sample biotech records."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

RULE_WEIGHTS = {
    "unknown_source": 2,
    "temperature_break": 2,
    "missing_label": 1,
    "contamination_note": 3,
}


def score_row(row: dict[str, str]) -> tuple[int, list[str]]:
    score = 0
    reasons: list[str] = []
    for rule, weight in RULE_WEIGHTS.items():
        if row.get(rule, "no").strip().lower() == "yes":
            score += weight
            reasons.append(rule.replace("_", " "))
    return score, reasons


def category(score: int) -> str:
    if score >= 4:
        return "high review priority"
    if score >= 2:
        return "medium review priority"
    return "low review priority"


def main() -> None:
    parser = argparse.ArgumentParser(description="Screen sample biotech records with explainable rules.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    print("BioSentinel Risk-Screening Demo")
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            score, reasons = score_row(row)
            reason_text = ", ".join(reasons) if reasons else "no flagged rules"
            print(f"{row['sample_id']}: score={score}, {category(score)} ({reason_text})")


if __name__ == "__main__":
    main()
'''
        return ProjectFiles("biosentinel_risk_screening_demo.py", "sample_screening.csv", "sample_id,unknown_source,temperature_break,missing_label,contamination_note\nS1,no,no,no,no\nS2,yes,no,yes,no\nS3,yes,yes,no,yes\n", code, "S1: score=0, low review priority (no flagged rules)\nS2: score=3, medium review priority (unknown source, missing label)\nS3: score=7, high review priority (unknown source, temperature break, contamination note)\n")
    code = '''"""Check a biotech CSV file for missing values before analysis."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize basic quality checks for a biotech CSV file.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        rows = list(csv.DictReader(file))
    missing = sum(1 for row in rows for value in row.values() if not value.strip())
    print("Biotech CSV Quality Summary")
    print(f"Rows checked: {len(rows)}")
    print(f"Missing values found: {missing}")


if __name__ == "__main__":
    main()
'''
    return ProjectFiles("biotech_csv_quality_summary.py", "sample_quality.csv", "sample,value,unit\nA,12,ng/uL\nB,,ng/uL\n", code, "Rows checked: 2\nMissing values found: 1\n")


def readme_for(item: dict[str, str], files: ProjectFiles) -> str:
    return clean_public_text(f"""# {item['title']}

**Portfolio:** Computational Biotechnology Portfolio  
**Track:** {TRACKS[item['folder']]}  
**Author:** Meena Vignesh M

## Purpose
This project turns a small biotechnology or healthcare-data task into a reproducible Python workflow. I built it to practice both the science concept and the coding steps clearly.

## Biology / Data Concept
{item['biology_concept']}

## How To Run

```bash
python {files.script_name} {files.sample_name}
```

## Files
- `{files.script_name}` - main Python script
- `{files.sample_name}` - sample input data
- `example_output.txt` - expected output example

## Job Skill Demonstrated
- Python scripting
- CSV/FASTA data handling
- Basic biotechnology interpretation
- Reproducible command-line workflow
- Scientific reporting

## Result
This tool converts raw biological/lab data into a clean summary report.

## What I Practiced
- {item['job_skill']}
- {item['python_concept']}
- Writing a README that explains the project like a scientific mini-report
""") + "\n"


def line_explanation(code: str) -> str:
    lines = ["Line-by-line code explanation:", ""]
    for number, line in enumerate(code.splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            meaning = "Blank space to keep the code readable."
        elif stripped.startswith('"""'):
            meaning = "States the purpose of the script."
        elif stripped.startswith("from __future__"):
            meaning = "Keeps modern Python type-hint behavior consistent."
        elif stripped.startswith("import ") or stripped.startswith("from "):
            meaning = "Loads a Python tool used later in the script."
        elif stripped.startswith("def "):
            meaning = "Starts a reusable function for one clear task."
        elif stripped.startswith("return "):
            meaning = "Sends a result back from the function."
        elif "argparse" in stripped or "add_argument" in stripped:
            meaning = "Lets the script accept a file name from the command line."
        elif "csv" in stripped:
            meaning = "Reads or writes structured table data."
        elif "print(" in stripped:
            meaning = "Shows the final result in the terminal."
        elif stripped.startswith("if __name__"):
            meaning = "Runs the script only when this file is opened directly."
        else:
            meaning = "Supports the main analysis logic."
        lines.append(f"Line {number}: {line}")
        lines.append(f"Explanation: {meaning}")
        lines.append("")
    return "\n".join(lines)


def email_body(item: dict[str, str], files: ProjectFiles) -> str:
    link = f"{REPO_URL}/tree/main/{item['folder']}/{item['slug']}"
    return clean_public_text(f"""Today's biotech job skill:
{item['job_skill']}

Project built:
{item['title']}
Repository: {link}

Python concept learned:
{item['python_concept']}

Biology concept learned:
{item['biology_concept']}

How to explain this in interview:
I built a small Python tool that accepts real-looking biotech or healthcare data, processes it step by step, and produces a clean result that a lab or data team could review. The main value is that I can connect biology concepts with reproducible data handling.

One resume bullet:
- {item['resume']}

Full code:

{files.script_name}
```python
{files.code}
```

{line_explanation(files.code)}
""")


def send_lesson(subject: str, body: str) -> None:
    to_email = os.getenv("LESSON_EMAIL_TO")
    host = os.getenv("SMTP_HOST")
    username = os.getenv("SMTP_USERNAME")
    password = os.getenv("SMTP_PASSWORD")
    port = int(os.getenv("SMTP_PORT", "587"))
    if not all([to_email, host, username, password]):
        print("Email settings are incomplete; skipping lesson email.")
        return
    try:
        message = EmailMessage()
        message["Subject"] = subject
        message["From"] = username
        message["To"] = to_email
        message.set_content(body)
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.starttls()
            server.login(username, password)
            server.send_message(message)
    except Exception as exc:
        print(f"Lesson email failed, but project files were created: {exc}")


def append_resume_bullet(item: dict[str, str]) -> None:
    header = "# Resume Bullets\n\nThese are portfolio-ready bullets I can adapt for internship and entry-level applications.\n\n"
    bullet = f"- {item['resume']}"
    if RESUME_PATH.exists():
        text = RESUME_PATH.read_text(encoding="utf-8")
    else:
        text = header
    if bullet not in text:
        if not text.endswith("\n"):
            text += "\n"
        text += bullet + "\n"
    RESUME_PATH.write_text(clean_public_text(text) + "\n", encoding="utf-8")


def write_project(item: dict[str, str]) -> None:
    files = make_files(item["kind"])
    folder = project_path(item)
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "README.md").write_text(readme_for(item, files), encoding="utf-8")
    (folder / files.sample_name).write_text(files.sample_content, encoding="utf-8")
    (folder / files.script_name).write_text(clean_public_text(files.code), encoding="utf-8")
    (folder / "example_output.txt").write_text(files.example_output, encoding="utf-8")
    append_resume_bullet(item)
    send_lesson(f"Biotech job skill lesson - {item['title']}", email_body(item, files))
    print(f"Created {TRACKS[item['folder']]} project: {item['title']}")


def main() -> None:
    item = next_project()
    write_project(item)


if __name__ == "__main__":
    main()
