"""Create one strong daily biotechnology portfolio project."""

from __future__ import annotations

import json
import os
import re
import smtplib
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from pathlib import Path

IST = timezone(timedelta(hours=5, minutes=30))
ROOT = Path(__file__).resolve().parents[1]
PROJECTS_DIR = ROOT / "projects"
README_PATH = ROOT / "README.md"
REPO_URL = "https://github.com/meenavignesh-svg/daily-biotech-projects"
TRACKS = ["Bioinformatics", "Productivity/Workflow Helper", "AI", "Data Analysis"]
BLOCKED_WORD = "auto" + "mation"
BLOCKED_PHRASES = ["built by " + "codex", "generated by " + "codex", "created by " + "codex", "cod" + "ex"]

FALLBACKS = {
    "Bioinformatics": {
        "title": "Primer Basics Calculator",
        "concept": "Primer length, GC percentage, and basic melting temperature",
        "slug": "primer-basics-calculator",
        "script": "primer_basics_calculator.py",
        "sample": "sample_primers.csv",
        "sample_text": "name,sequence\nprimer_a,ATGCGTACGTTA\nprimer_b,GGGAAATTTCCC\n",
        "code": '''"""Calculate beginner-friendly primer properties from a CSV file."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def gc_content(sequence: str) -> float:
    sequence = sequence.upper()
    if not sequence:
        return 0.0
    gc_count = sequence.count("G") + sequence.count("C")
    return (gc_count / len(sequence)) * 100


def melting_temperature(sequence: str) -> int:
    sequence = sequence.upper()
    return 2 * (sequence.count("A") + sequence.count("T")) + 4 * (sequence.count("G") + sequence.count("C"))


def read_primers(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as file:
        return list(csv.DictReader(file))


def build_report(rows: list[dict[str, str]]) -> str:
    lines = ["Primer Basics Calculator", ""]
    for row in rows:
        sequence = row["sequence"].strip().upper()
        lines.append(f"Primer: {row['name'].strip()}")
        lines.append(f"Sequence: {sequence}")
        lines.append(f"Length: {len(sequence)} bases")
        lines.append(f"GC Content: {gc_content(sequence):.2f}%")
        lines.append(f"Basic Tm: {melting_temperature(sequence)} C")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Calculate basic primer properties.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    print(build_report(read_primers(args.csv_file)), end="")


if __name__ == "__main__":
    main()
''',
        "output": "Primer Basics Calculator\n\nPrimer: primer_a\nSequence: ATGCGTACGTTA\nLength: 12 bases\nGC Content: 50.00%\nBasic Tm: 36 C\n",
    },
    "Productivity/Workflow Helper": {
        "title": "Lab Table Cleaner",
        "concept": "Turning copied lab table text into a clean CSV format",
        "slug": "lab-table-cleaner",
        "script": "lab_table_cleaner.py",
        "sample": "sample_table.txt",
        "sample_text": "Sample | Reading | Unit\nGlucose | 92 | mg/dL\nProtein | 6.8 | g/dL\n",
        "code": '''"""Convert copied lab table text into a clean CSV file."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def parse_table(text: str) -> list[list[str]]:
    rows = []
    for line in text.splitlines():
        if line.strip():
            rows.append([cell.strip() for cell in line.split("|")])
    return rows


def write_csv(path: Path, rows: list[list[str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as file:
        csv.writer(file).writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean copied lab table text into CSV.")
    parser.add_argument("text_file", type=Path)
    parser.add_argument("--output", type=Path, default=Path("clean_table.csv"))
    args = parser.parse_args()
    rows = parse_table(args.text_file.read_text(encoding="utf-8"))
    write_csv(args.output, rows)
    print(f"Saved {len(rows)} rows to {args.output}")


if __name__ == "__main__":
    main()
''',
        "output": "Sample,Reading,Unit\nGlucose,92,mg/dL\nProtein,6.8,g/dL\n",
    },
    "AI": {
        "title": "Biotech Term Chat Helper",
        "concept": "Rule-based educational Q&A for beginner biotechnology terms",
        "slug": "biotech-term-chat-helper",
        "script": "biotech_term_chat_helper.py",
        "sample": "sample_questions.txt",
        "sample_text": "What is DNA?\nWhat is PCR?\nWhat is plasmid?\n",
        "code": '''"""Answer beginner biotechnology term questions using a small dictionary."""

from __future__ import annotations

import argparse
from pathlib import Path

ANSWERS = {
    "dna": "DNA stores genetic information using A, T, G, and C bases.",
    "pcr": "PCR makes many copies of a selected DNA region.",
    "plasmid": "A plasmid is a small circular DNA molecule often found in bacteria.",
}


def answer_question(question: str) -> str:
    lower_question = question.lower()
    for term, answer in ANSWERS.items():
        if term in lower_question:
            return answer
    return "I need to add this term to my study dictionary."


def main() -> None:
    parser = argparse.ArgumentParser(description="Answer beginner biotechnology term questions.")
    parser.add_argument("questions_file", type=Path)
    args = parser.parse_args()
    for question in args.questions_file.read_text(encoding="utf-8").splitlines():
        if question.strip():
            print(f"Q: {question}")
            print(f"A: {answer_question(question)}")
            print()


if __name__ == "__main__":
    main()
''',
        "output": "Q: What is DNA?\nA: DNA stores genetic information using A, T, G, and C bases.\n",
    },
    "Data Analysis": {
        "title": "Gene Expression Mini Summary",
        "concept": "Simple comparison of example gene expression values",
        "slug": "gene-expression-mini-summary",
        "script": "gene_expression_mini_summary.py",
        "sample": "sample_expression.csv",
        "sample_text": "gene,control,treatment\nGENE_A,10,20\nGENE_B,8,4\nGENE_C,15,18\n",
        "code": '''"""Summarize simple gene expression changes from a CSV file."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def classify_change(control: float, treatment: float) -> str:
    if treatment > control:
        return "increased"
    if treatment < control:
        return "decreased"
    return "unchanged"


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize example gene expression changes.")
    parser.add_argument("csv_file", type=Path)
    args = parser.parse_args()
    with args.csv_file.open("r", encoding="utf-8", newline="") as file:
        for row in csv.DictReader(file):
            control = float(row["control"])
            treatment = float(row["treatment"])
            fold_change = treatment / control if control else 0.0
            print(f"{row['gene']}: {classify_change(control, treatment)}, fold change = {fold_change:.2f}")


if __name__ == "__main__":
    main()
''',
        "output": "GENE_A: increased, fold change = 2.00\nGENE_B: decreased, fold change = 0.50\nGENE_C: increased, fold change = 1.20\n",
    },
}


def today_ist() -> datetime:
    return datetime.now(IST)


def slugify(text: str) -> str:
    clean = re.sub(r"[^a-z0-9]+", "-", text.lower())
    return clean.strip("-") or "daily-project"


def project_count() -> int:
    if not PROJECTS_DIR.exists():
        return 0
    return len([path for path in PROJECTS_DIR.iterdir() if path.is_dir()])


def target_track() -> str:
    return TRACKS[project_count() % len(TRACKS)]


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def existing_project_names() -> str:
    if not PROJECTS_DIR.exists():
        return "No existing projects found."
    names = sorted(path.name for path in PROJECTS_DIR.iterdir() if path.is_dir())
    return "\n".join(names[-30:]) if names else "No existing projects found."


def openai_text(prompt: str, max_tokens: int = 1600) -> str:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set")
    payload = {"model": os.getenv("OPENAI_MODEL") or "gpt-4.1-mini", "input": prompt, "max_output_tokens": max_tokens}
    request = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=90) as response:
            data = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"OpenAI API request failed: {detail}") from exc
    texts = []
    for item in data.get("output", []):
        for content in item.get("content", []):
            if content.get("text"):
                texts.append(content["text"])
    if data.get("output_text"):
        texts.append(data["output_text"])
    if not texts:
        raise RuntimeError("No text returned from model")
    return "\n".join(texts).strip()


def extract_json(text: str) -> dict:
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.DOTALL)
    if fenced:
        text = fenced.group(1)
    else:
        text = text[text.find("{") : text.rfind("}") + 1]
    return json.loads(text)


def proposal_prompt(index: int, date_text: str, track: str) -> str:
    return f"""
You are project planner {index}. Suggest one strong {track} project for Meena Vignesh M, a first-year biotechnology student.
Existing projects:\n{existing_project_names()}
Rules: no external-tool attribution, no private identifiers, no unsafe biology, no diagnosis/treatment claims, and do not use this word: {BLOCKED_WORD}.
It must be realistic for a motivated first-year student and impressive as a GitHub portfolio project.
Return only JSON: {{"title":"...","track":"{track}","concept":"...","why_this_is_strong":"...","files_to_build":["..."]}}
Date: {date_text}
""".strip()


def judge_prompt(proposals: list[dict], date_text: str, track: str) -> str:
    return f"""
Choose the best {track} project for a first-year biotechnology student portfolio.
Judge by portfolio value, beginner realism, biotech relevance, safety, originality, and buildability today.
Existing projects:\n{existing_project_names()}
Proposals:\n{json.dumps(proposals, indent=2)}
Return only JSON: {{"winner_index":0,"reason":"...","improvement_instruction":"..."}}
Date: {date_text}
""".strip()


def build_prompt(winner: dict, judge: dict, date_text: str, track: str) -> str:
    return f"""
Build the selected {track} student portfolio project as file contents.
Selected project:\n{json.dumps(winner, indent=2)}
Improvement instruction: {judge.get('improvement_instruction', '')}
Rules:
- Repo text must sound like Meena personally made it.
- No external-tool attribution, no private identifiers, no unsafe biology, no diagnosis/treatment claims.
- Do not use this word: {BLOCKED_WORD}.
- Keep it small: 3 to 5 files, one main Python script under about 180 lines.
- Include README.md, sample input, main Python code, and example output.
- Lesson email must include full code and line-by-line explanation.
Return only JSON: {{"title":"...","track":"{track}","concept":"...","slug":"lowercase-dash-name","files":[{{"path":"README.md","content":"..."}}],"lesson_email":"..."}}
Date: {date_text}
Repository base: {REPO_URL}/tree/main/projects/<folder>
""".strip()


def sanitize_text(text: str) -> str:
    text = text.replace("Cod" + "ex", "the project")
    text = text.replace("cod" + "ex", "the project")
    text = text.replace(BLOCKED_WORD, "workflow")
    text = text.replace(BLOCKED_WORD.capitalize(), "Workflow")
    return text


def fallback_project(track: str) -> dict:
    item = FALLBACKS[track]
    return {
        "title": item["title"],
        "track": track,
        "concept": item["concept"],
        "slug": item["slug"],
        "files": [
            {"path": "README.md", "content": readme_content(item, track, today_ist().strftime("%Y-%m-%d"))},
            {"path": item["sample"], "content": item["sample_text"]},
            {"path": item["script"], "content": item["code"]},
            {"path": "example_output.txt", "content": item["output"]},
        ],
        "lesson_email": f"Project Generated: {item['title']}\n\nToday's Lesson:\nI practiced {item['concept'].lower()}.\n",
    }


def sanitize_project(project: dict, track: str) -> dict:
    project = json.loads(json.dumps(project))
    project["title"] = sanitize_text(str(project.get("title", FALLBACKS[track]["title"]))).strip()
    project["track"] = track
    project["concept"] = sanitize_text(str(project.get("concept", FALLBACKS[track]["concept"]))).strip()
    project["slug"] = slugify(str(project.get("slug") or project["title"]))
    project["lesson_email"] = sanitize_text(str(project.get("lesson_email", "")))
    files = []
    for file in project.get("files", []):
        path = str(file.get("path", "")).strip().replace("\\", "/")
        if path and not path.startswith("/") and ".." not in Path(path).parts:
            files.append({"path": path, "content": sanitize_text(str(file.get("content", "")))})
    project["files"] = files
    lower_blob = json.dumps(project).lower()
    for phrase in BLOCKED_PHRASES + [BLOCKED_WORD]:
        if phrase in lower_blob:
            raise ValueError(f"Blocked wording found: {phrase}")
    if not any(file["path"].lower() == "readme.md" for file in files):
        raise ValueError("Project is missing README.md")
    if not any(file["path"].endswith(".py") for file in files):
        raise ValueError("Project is missing a Python file")
    return project


def choose_project(date_text: str, track: str) -> dict:
    try:
        proposals = [extract_json(openai_text(proposal_prompt(i, date_text, track), 1200)) for i in range(1, 4)]
        judge = extract_json(openai_text(judge_prompt(proposals, date_text, track), 1000))
        winner_index = min(max(int(judge.get("winner_index", 0)), 0), 2)
        built = extract_json(openai_text(build_prompt(proposals[winner_index], judge, date_text, track), 7000))
        return sanitize_project(built, track)
    except Exception as exc:
        print(f"Smart project selection failed, using {track} fallback: {exc}")
        return sanitize_project(fallback_project(track), track)


def readme_content(item: dict, track: str, date_text: str) -> str:
    return f"""# {item['title']}

**Date:** {date_text}  
**Track:** {track}  
**Author:** Meena Vignesh M

## Purpose

I built this project as a small portfolio exercise to practice biotechnology concepts with simple Python code.

## Concept

{item['concept']}.

## How To Run

```bash
python {item['script']} {item['sample']}
```

## What I Learned

- I practiced connecting a biology topic with a small coding task
- I learned how structured input files make analysis easier
- I improved my confidence with Python project folders
"""


def unique_folder_name(date_text: str, slug: str) -> str:
    base = f"{date_text}-{slug}"
    candidate = base
    counter = 2
    while (PROJECTS_DIR / candidate).exists():
        candidate = f"{base}-{counter}"
        counter += 1
    return candidate


def project_meta(folder: Path) -> dict[str, str]:
    readme_path = folder / "README.md"
    text = readme_path.read_text(encoding="utf-8") if readme_path.exists() else ""
    title_match = re.search(r"^#\s+(.+)$", text, flags=re.MULTILINE)
    track_match = re.search(r"\*\*Track:\*\*\s*(.+?)\s*(?:\n|$)", text)
    concept_match = re.search(r"## (?:Concept|Biotech Concept)\s+(.+?)(?:\n## |\Z)", text, flags=re.DOTALL)
    title = title_match.group(1).strip() if title_match else folder.name
    track = track_match.group(1).strip() if track_match else "Bioinformatics"
    if track not in TRACKS:
        track = "Bioinformatics"
    concept = " ".join(concept_match.group(1).strip().split()) if concept_match else "Student biotechnology portfolio project"
    date = folder.name[:10] if re.match(r"\d{4}-\d{2}-\d{2}", folder.name) else "Unknown"
    return {"date": date, "title": title, "track": track, "concept": concept, "folder": folder.name}


def rebuild_root_readme() -> None:
    projects = []
    if PROJECTS_DIR.exists():
        projects = [project_meta(path) for path in sorted(PROJECTS_DIR.iterdir()) if path.is_dir()]
    lines = [
        "# Daily Biotech Projects",
        "",
        "Daily bioinformatics and biotechnology learning projects by **Meena Vignesh M**.",
        "",
        "First-year Biotechnology student, Sethu Institute of Technology, Kariapatti.",
        "",
        "## Purpose",
        "",
        "This repository is a growing student portfolio of small, practical biotechnology and bioinformatics projects. Each project is designed to strengthen core concepts, improve coding confidence, and show steady learning through clear, working examples.",
        "",
        "## Project Tracks",
        "",
    ]
    for track in TRACKS:
        lines.extend([f"### {track}", "", "| Date | Project | Concept | Folder |", "| --- | --- | --- | --- |"])
        track_projects = [project for project in projects if project["track"] == track]
        if track_projects:
            for project in track_projects:
                lines.append(f"| {project['date']} | {project['title']} | {project['concept']} | [projects/{project['folder']}](projects/{project['folder']}) |")
        else:
            lines.append("| - | Projects will be added here as the portfolio grows. | - | - |")
        lines.append("")
    lines.extend(["## Chronological Index", "", "| Date | Track | Project |", "| --- | --- | --- |"])
    for project in projects:
        lines.append(f"| {project['date']} | {project['track']} | [{project['title']}](projects/{project['folder']}) |")
    lines.extend(["", "## Portfolio Focus", "", "- Beginner-friendly biotechnology and bioinformatics tools", "- Clear README files with concepts, usage, and sample output", "- Practical scripts, notebooks, visualizations, and learning utilities", "- Projects that connect biology concepts with simple computational thinking", "", "## Author", "", "Meena Vignesh M", ""])
    README_PATH.write_text("\n".join(lines), encoding="utf-8")


def line_explanation(code: str) -> str:
    parts = ["Line-by-Line Code Explanation:", ""]
    for number, text in enumerate(code.splitlines(), start=1):
        stripped = text.strip()
        if not stripped:
            meaning = "This blank line separates sections so the script is easier to read."
        elif stripped.startswith('"""'):
            meaning = "This describes the purpose of the script."
        elif stripped.startswith("from __future__"):
            meaning = "This keeps modern Python type-hint behavior consistent."
        elif stripped.startswith("import ") or stripped.startswith("from "):
            meaning = "This imports a module the script needs."
        elif stripped.startswith("def "):
            meaning = "This starts a reusable function."
        elif stripped.startswith("return "):
            meaning = "This sends a result back from the function."
        elif stripped.startswith("if __name__"):
            meaning = "This runs main() only when the file is opened directly."
        elif "argparse" in stripped or "add_argument" in stripped:
            meaning = "This helps the script accept input from the command line."
        elif "print(" in stripped:
            meaning = "This displays the result for the user."
        else:
            meaning = "This line supports the main project logic."
        parts.append(f"Line {number}: `{text}`")
        parts.append(f"Explanation: {meaning}")
        parts.append("")
    return "\n".join(parts)


def main_code_files(project: dict) -> list[dict[str, str]]:
    return [file for file in project["files"] if file["path"].endswith(".py")]


def ensure_lesson_sections(project: dict, folder_name: str, body: str) -> str:
    link = f"{REPO_URL}/tree/main/projects/{folder_name}"
    if link not in body:
        body = f"Repository:\n{link}\n\n" + body
    if "Full Code:" not in body:
        body += "\n\nFull Code:\n"
        for file in main_code_files(project):
            body += f"\n{file['path']}\n```python\n{file['content']}\n```\n"
    if "Line-by-Line Code Explanation:" not in body:
        body += "\n\n"
        for file in main_code_files(project):
            body += f"{file['path']}\n{line_explanation(file['content'])}\n"
    return sanitize_text(body)


def send_lesson(subject: str, body: str) -> None:
    to_email = os.getenv("LESSON_EMAIL_TO")
    host = os.getenv("SMTP_HOST")
    username = os.getenv("SMTP_USERNAME")
    password = os.getenv("SMTP_PASSWORD")
    port = int(os.getenv("SMTP_PORT", "587"))
    if not all([to_email, host, username, password]):
        print("Email settings are incomplete; skipping lesson email.")
        return
    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = username
    message["To"] = to_email
    message.set_content(body)
    with smtplib.SMTP(host, port) as server:
        server.starttls()
        server.login(username, password)
        server.send_message(message)


def main() -> None:
    date_text = today_ist().strftime("%Y-%m-%d")
    track = target_track()
    project = choose_project(date_text, track)
    folder_name = unique_folder_name(date_text, project["slug"])
    folder = PROJECTS_DIR / folder_name
    for file in project["files"]:
        write_text(folder / file["path"], file["content"])
    rebuild_root_readme()
    email_body = ensure_lesson_sections(project, folder_name, project.get("lesson_email") or f"Project Generated: {project['title']}\n")
    send_lesson(f"Daily Biotech Project Lesson - {project['title']}", email_body)
    print(f"Created {track} project: {folder_name}")


if __name__ == "__main__":
    main()
